'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, BadgeIndianRupee, Clock3, MapPinned, Recycle, ShieldCheck, ShoppingBasket, Sparkles, Truck } from 'lucide-react';
import { addToPickupCart } from '@/lib/pickupCart';

const icons = ['📄', '📦', '♻️', '🔩', '💻', '🍾', '🛋️', '✨'];

export default function HomePage() {
  const [categories, setCategories] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState('');
  useEffect(() => { fetch('/api/waste-categories').then((r) => r.json()).then((d) => setCategories(d.success ? d.data : [])).catch(() => setCategories([])).finally(() => setLoading(false)); }, []);
  const featured = useMemo(() => categories.slice(0, 10), [categories]);
  const addCategory = (category: any) => { addToPickupCart(category.id); setNotice(`${category.name} added to your Pickup Cart`); window.setTimeout(() => setNotice(''), 2200); };

  return <div className="min-h-screen bg-[#f8faf8] pb-24">
    {notice && <div className="fixed bottom-24 left-1/2 z-50 -translate-x-1/2 rounded-2xl bg-slate-950 px-4 py-3 text-xs font-bold text-white shadow-2xl">{notice}</div>}
    <section className="relative overflow-hidden bg-slate-950"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_10%,rgba(16,185,129,.36),transparent_32%),radial-gradient(circle_at_20%_100%,rgba(251,191,36,.16),transparent_28%)]" /><div className="relative mx-auto grid max-w-7xl gap-10 px-4 py-12 sm:px-6 md:grid-cols-[1.1fr_.9fr] md:py-20">
      <div className="max-w-2xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1.5 text-xs font-black text-emerald-300"><Sparkles className="h-3.5 w-3.5" />BENGALURU DOORSTEP PICKUP</div><h1 className="text-4xl font-black leading-[1.02] tracking-tight text-white sm:text-6xl">Turn your waste <span className="text-emerald-400">into value.</span></h1><p className="mt-5 max-w-xl text-base leading-relaxed text-slate-300 sm:text-lg">Add what you have, choose your doorstep and time, then track your pickup from booking to settlement.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/book?cart=1" className="inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl bg-emerald-400 px-6 text-sm font-black text-slate-950 shadow-xl shadow-emerald-500/15"><ShoppingBasket className="h-5 w-5" />Book a Pickup<ArrowRight className="h-4 w-4" /></Link><a href="#categories" className="inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl border border-white/20 px-6 text-sm font-bold text-white hover:bg-white/10">Explore waste categories</a></div><div className="mt-8 grid grid-cols-3 gap-3 text-xs"><div className="rounded-2xl border border-white/10 bg-white/5 p-3 text-slate-200"><Clock3 className="mb-2 h-5 w-5 text-emerald-400" /><strong className="block text-white">Pick a time</strong>ASAP or scheduled</div><div className="rounded-2xl border border-white/10 bg-white/5 p-3 text-slate-200"><BadgeIndianRupee className="mb-2 h-5 w-5 text-emerald-400" /><strong className="block text-white">Clear value</strong>Rates shown upfront</div><div className="rounded-2xl border border-white/10 bg-white/5 p-3 text-slate-200"><Recycle className="mb-2 h-5 w-5 text-emerald-400" /><strong className="block text-white">Recycle right</strong>Responsible handling</div></div></div>
      <div className="relative hidden min-h-96 items-end md:flex"><div className="absolute right-0 top-8 h-72 w-72 rounded-full border-[20px] border-emerald-400/15" /><div className="relative w-full rounded-[2.5rem] border border-white/10 bg-gradient-to-br from-emerald-400 to-emerald-600 p-7 shadow-2xl"><div className="rounded-3xl bg-white p-5 text-slate-950"><div className="flex items-center justify-between"><span className="text-xs font-black text-emerald-700">YOUR PICKUP, SIMPLIFIED</span><Truck className="h-7 w-7 text-emerald-600" /></div><div className="mt-7 space-y-3"><div className="rounded-2xl bg-slate-100 p-3 text-sm font-bold">1. Add waste to Pickup Cart</div><div className="rounded-2xl bg-slate-100 p-3 text-sm font-bold">2. Share your pickup spot</div><div className="rounded-2xl bg-slate-950 p-3 text-sm font-black text-white">3. Track your agent live</div></div></div></div></div>
    </div></section>
    <main className="mx-auto max-w-7xl space-y-12 px-4 py-10 sm:px-6"><section id="categories"><div className="mb-5 flex items-end justify-between gap-4"><div><p className="text-xs font-black tracking-[.16em] text-emerald-700">START WITH WHAT YOU HAVE</p><h2 className="mt-1 text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">Add waste to your Pickup Cart</h2></div><Link href="/categories" className="shrink-0 text-sm font-black text-emerald-700">See all <ArrowRight className="inline h-4 w-4" /></Link></div><div className="flex snap-x gap-3 overflow-x-auto pb-3 [scrollbar-width:none]">{loading ? Array.from({ length: 6 }).map((_, index) => <div key={index} className="h-40 w-32 shrink-0 animate-pulse rounded-3xl bg-slate-200" />) : featured.map((category, index) => <article key={category.id} className="w-36 shrink-0 snap-start rounded-3xl border border-slate-200 bg-white p-3 shadow-sm transition hover:-translate-y-1 hover:border-emerald-300 hover:shadow-lg sm:w-40"><Link href={`/book?category=${encodeURIComponent(category.id)}`} className="block"><div className="grid h-20 place-items-center rounded-2xl bg-emerald-50 text-4xl">{icons[index % icons.length]}</div><h3 className="mt-3 line-clamp-2 min-h-10 text-sm font-black leading-tight text-slate-900">{category.name}</h3><p className="mt-1 text-[11px] font-bold text-emerald-700">₹{category.pricePerKg}/kg</p></Link><button onClick={() => addCategory(category)} className="mt-3 w-full rounded-xl bg-slate-950 px-2 py-2 text-[11px] font-black text-white hover:bg-emerald-600">Add</button></article>)}</div></section>
      <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{icon:Truck,title:'Doorstep pickup',copy:'A simple pickup request from home or work.'},{icon:Clock3,title:'Fast & easy booking',copy:'Choose ASAP or a time that suits you.'},{icon:BadgeIndianRupee,title:'Sell recyclables',copy:'See estimates before you confirm.'},{icon:MapPinned,title:'Track your pickup',copy:'Follow status updates and your agent.'}].map(({icon: Icon,title,copy}) => <div key={title} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-emerald-100 text-emerald-700"><Icon className="h-5 w-5" /></span><h3 className="mt-4 font-black text-slate-950">{title}</h3><p className="mt-1 text-sm leading-relaxed text-slate-500">{copy}</p></div>)}</section>
      <section className="grid gap-5 rounded-[2rem] bg-emerald-50 p-6 md:grid-cols-[1fr_auto] md:items-center md:p-8"><div><div className="inline-flex items-center gap-2 text-xs font-black text-emerald-800"><ShieldCheck className="h-4 w-4" />CLEANER HOMES. CLEANER BENGALURU.</div><h2 className="mt-2 text-2xl font-black text-slate-950">Already booked a pickup?</h2><p className="mt-1 text-sm text-slate-600">Review your pickup status, agent details, receipts, and past requests in one place.</p></div><Link href="/customer/orders" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-slate-950 px-5 text-sm font-black text-white">My Pickups <ArrowRight className="h-4 w-4" /></Link></section>
    </main></div>;
}
